formatter: "markdown"

sections:
  show:
    - outputs

content: |-
  {{ .Outputs }}

output:
  file: "output.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->


output-values:
  enabled: false
  from: "output_values.json"

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true