formatter: "markdown"

sections:
  show:
    - outputs

output:
  file: "atmos-apply-summary.md"
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }}
    
    [//]: # (END_TF_DOCS)

output-values:
  enabled: true
  from: "output_values.json"

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: false
  type: true