formatter: "markdown"

sections:
  show:
    - outputs

content: |-
  {{- if .Config.Sections.Outputs -}}
      {{- if not .Module.Outputs -}}
          {{- if not .Config.Settings.HideEmpty -}}
              {{- indent 0 "#" }} Outputs
  
              No outputs.
          {{ end }}
      {{ else }}
          {{- indent 0 "#" }} Outputs
  
          | Name | Description |{{ if .Config.OutputValues.Enabled }} Value |{{ end }}
          |------|-------------|{{ if .Config.OutputValues.Enabled }}-------|{{ end }}
          {{- range .Module.Outputs }}
              | {{ anchorNameMarkdown "output" .Name }} | {{ tostring .Description | sanitizeMarkdownTbl }} |
              {{- if $.Config.OutputValues.Enabled -}}
                  {{- $sensitive := ternary .Sensitive "<sensitive>" .GetValue -}}
                  {{ printf " " }}{{ value $sensitive | sanitizeMarkdownTbl }} |
              {{- end -}}
          {{- end }}
      {{ end }}
  {{ end -}}

output:
  file: "atmos-apply-summary.md"
  mode: inject
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }}
    
    [//]: # (END_TF_DOCS)

output-values:
  enabled: true
  from: "output_values.json"

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true