name: "Integration Tests"

on:
  workflow_dispatch: {}

  pull_request:
    types: [opened, synchronize, reopened]

env:
  AWS_REGION: us-east-2

# Permissions required for assuming AWS identity
permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir -p ${{ runner.temp }}
          cat > ${{ runner.temp }}/atmos-gitops.yaml <<EOL
          atmos-version: 1.45.3
          atmos-config-path: ./tests/
          terraform-state-bucket: ${{ secrets.TERRAFORM_STATE_BUCKET }}
          terraform-state-table: ${{ secrets.TERRAFORM_STATE_TABLE }}
          terraform-state-role: ${{ secrets.TERRAFORM_STATE_ROLE }}
          terraform-plan-role: ${{ secrets.TERRAFORM_APPLY_ROLE }}
          terraform-version: 1.5.2
          aws-region: ${{ env.AWS_REGION }}
          sort-by: .stack_slug
          group-by: .stack_slug | split("-") | [.[0], .[2]] | join("-")          
          EOL

      - name: Plan Atmos Component
        uses: cloudposse/github-action-atmos-terraform-plan@incapsulate-configs
        with:
          component: "foobar"
          stack: "plat-ue2-sandbox"
          atmos-gitops-config-path: "${{ runner.temp }}/atmos-gitops.yaml"
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - shell: bash
        run: |
          mkdir -p ${{ runner.temp }}
          cat > ${{ runner.temp }}/atmos-gitops.yaml <<EOL
          atmos-version: 1.45.3
          atmos-config-path: ./tests/
          terraform-state-bucket: ${{ secrets.TERRAFORM_STATE_BUCKET }}
          terraform-state-table: ${{ secrets.TERRAFORM_STATE_TABLE }}
          terraform-state-role: ${{ secrets.TERRAFORM_STATE_ROLE }}
          terraform-plan-role: ${{ secrets.TERRAFORM_APPLY_ROLE }}
          terraform-apply-role: ${{ secrets.TERRAFORM_APPLY_ROLE }}          
          terraform-version: 1.5.2
          aws-region: ${{ env.AWS_REGION }}
          sort-by: .stack_slug
          group-by: .stack_slug | split("-") | [.[0], .[2]] | join("-")          
          EOL

      - name: Apply Atmos Component
        uses: ./
        with:
          component: "foobar"
          stack: "plat-ue2-sandbox"
          atmos-gitops-config-path: "${{ runner.temp }}/atmos-gitops.yaml"