name: "Test - Atmos Pro Enabled"

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

env:
  AWS_REGION: us-east-2

# Permissions required for assuming AWS identity
permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - shell: bash
        run: |
          mkdir -p ${{ runner.temp }}
          cp ./tests/terraform/atmos.yaml ${{ runner.temp }}/atmos.yaml
          sed -i -e 's#__INFRACOST_ENABLED__#false#g' ${{ runner.temp }}/atmos.yaml
          sed -i -e 's#__TERRAFORM_VERSION__#1.5.7#g' ${{ runner.temp }}/atmos.yaml
          sed -i -e 's#__OPENTOFU_VERSION__#1.6.0#g' ${{ runner.temp }}/atmos.yaml

      - name: Test Terraform Apply with Atmos Pro Enabled
        uses: ./
        with:
          component: foobar
          stack: catalog/foobar-atmos-pro
          atmos-config-path: ${{ runner.temp }}/atmos.yaml
          debug: true

      - name: Test OpenTofu Apply with Atmos Pro Enabled
        uses: ./
        with:
          component: foobar
          stack: catalog/foobar-atmos-pro
          atmos-config-path: ${{ runner.temp }}/atmos.yaml
          debug: true 